# Realistic property dataset for Kerala House Price Prediction comparison.
# Contains properties across various districts, locations, and specifications.

PROPERTIES_DATASET = [
    # Thiruvananthapuram (Kowdiar, Pattom, Kazhakkoottam)
    {
        "district": "Thiruvananthapuram",
        "location": "Kowdiar",
        "built_up_area_sqft": 2100,
        "plot_size_cents": 8.5,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 8500000.0
    },
    {
        "district": "Thiruvananthapuram",
        "location": "Pattom",
        "built_up_area_sqft": 1950,
        "plot_size_cents": 7.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 7800000.0
    },
    {
        "district": "Thiruvananthapuram",
        "location": "Kazhakkoottam",
        "built_up_area_sqft": 1600,
        "plot_size_cents": 5.5,
        "bedrooms": 3,
        "bathrooms": 2,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6200000.0
    },
    {
        "district": "Thiruvananthapuram",
        "location": "Kowdiar",
        "built_up_area_sqft": 2800,
        "plot_size_cents": 12.0,
        "bedrooms": 4,
        "bathrooms": 4,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 3,
        "kitchen_type": "Modular",
        "quality": "Luxury",
        "roof_type": "RCC",
        "flooring": "Marble",
        "price": 13500000.0
    },
    {
        "district": "Thiruvananthapuram",
        "location": "Vattiyoorkavu",
        "built_up_area_sqft": 1800,
        "plot_size_cents": 8.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "Sloped Roof",
        "flooring": "Vitrified Tile",
        "price": 6900000.0
    },
    {
        "district": "Thiruvananthapuram",
        "location": "Neyyattinkara",
        "built_up_area_sqft": 1200,
        "plot_size_cents": 5.0,
        "bedrooms": 2,
        "bathrooms": 2,
        "floors": 1,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Basic",
        "roof_type": "RCC",
        "flooring": "Cement",
        "price": 3800000.0
    },

    # Ernakulam (Kakkanad, Edappally, Aluva, Kaloor, Vyttila)
    {
        "district": "Ernakulam",
        "location": "Kakkanad",
        "built_up_area_sqft": 1850,
        "plot_size_cents": 6.5,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 7500000.0
    },
    {
        "district": "Ernakulam",
        "location": "Edappally",
        "built_up_area_sqft": 2200,
        "plot_size_cents": 8.0,
        "bedrooms": 4,
        "bathrooms": 4,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 9800000.0
    },
    {
        "district": "Ernakulam",
        "location": "Kaloor",
        "built_up_area_sqft": 2400,
        "plot_size_cents": 10.0,
        "bedrooms": 4,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 3,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 10500000.0
    },
    {
        "district": "Ernakulam",
        "location": "Vyttila",
        "built_up_area_sqft": 3000,
        "plot_size_cents": 15.0,
        "bedrooms": 5,
        "bathrooms": 5,
        "floors": 2,
        "parking_spaces": 3,
        "balconies": 4,
        "kitchen_type": "Modular",
        "quality": "Luxury",
        "roof_type": "RCC",
        "flooring": "Marble",
        "price": 16000000.0
    },
    {
        "district": "Ernakulam",
        "location": "Aluva",
        "built_up_area_sqft": 1500,
        "plot_size_cents": 6.0,
        "bedrooms": 3,
        "bathrooms": 2,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "Sloped Roof",
        "flooring": "Vitrified Tile",
        "price": 5800000.0
    },
    {
        "district": "Ernakulam",
        "location": "Angamaly",
        "built_up_area_sqft": 1350,
        "plot_size_cents": 5.5,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 1,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 4900000.0
    },
    {
        "district": "Ernakulam",
        "location": "Muvattupuzha",
        "built_up_area_sqft": 1700,
        "plot_size_cents": 8.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6200000.0
    },

    # Kozhikode (Chevayur, Calicut Beach, Nadakkavu, Mavoor)
    {
        "district": "Kozhikode",
        "location": "Nadakkavu",
        "built_up_area_sqft": 2050,
        "plot_size_cents": 7.5,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 8200000.0
    },
    {
        "district": "Kozhikode",
        "location": "Chevayur",
        "built_up_area_sqft": 1800,
        "plot_size_cents": 6.8,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 7100000.0
    },
    {
        "district": "Kozhikode",
        "location": "Mavoor",
        "built_up_area_sqft": 1400,
        "plot_size_cents": 6.0,
        "bedrooms": 3,
        "bathrooms": 2,
        "floors": 1,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "Sloped Roof",
        "flooring": "Vitrified Tile",
        "price": 4800000.0
    },

    # Thrissur (Kuriachira, Punkunnam, Ollur)
    {
        "district": "Thrissur",
        "location": "Punkunnam",
        "built_up_area_sqft": 2000,
        "plot_size_cents": 8.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 7900000.0
    },
    {
        "district": "Thrissur",
        "location": "Kuriachira",
        "built_up_area_sqft": 1750,
        "plot_size_cents": 7.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6600000.0
    },
    {
        "district": "Thrissur",
        "location": "Ollur",
        "built_up_area_sqft": 1500,
        "plot_size_cents": 6.0,
        "bedrooms": 3,
        "bathrooms": 2,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "Sloped Roof",
        "flooring": "Vitrified Tile",
        "price": 5400000.0
    },

    # Kottayam (Kanjikuzhy, Kumaranalloor)
    {
        "district": "Kottayam",
        "location": "Kanjikuzhy",
        "built_up_area_sqft": 2200,
        "plot_size_cents": 9.0,
        "bedrooms": 4,
        "bathrooms": 4,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 8900000.0
    },
    {
        "district": "Kottayam",
        "location": "Kumaranalloor",
        "built_up_area_sqft": 1600,
        "plot_size_cents": 7.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6100000.0
    },

    # General properties to fill in districts
    {
        "district": "Kollam",
        "location": "Kadavoor",
        "built_up_area_sqft": 1800,
        "plot_size_cents": 8.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6700000.0
    },
    {
        "district": "Alappuzha",
        "location": "Kalavoor",
        "built_up_area_sqft": 1600,
        "plot_size_cents": 6.0,
        "bedrooms": 3,
        "bathrooms": 2,
        "floors": 1,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 5600000.0
    },
    {
        "district": "Palakkad",
        "location": "Vidyut Nagar",
        "built_up_area_sqft": 1700,
        "plot_size_cents": 7.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 1,
        "kitchen_type": "Normal",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 5900000.0
    },
    {
        "district": "Kannur",
        "location": "Payyambalam",
        "built_up_area_sqft": 2100,
        "plot_size_cents": 8.5,
        "bedrooms": 4,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 2,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Premium",
        "roof_type": "RCC",
        "flooring": "Granite",
        "price": 8100000.0
    },
    {
        "district": "Malappuram",
        "location": "Down Hill",
        "built_up_area_sqft": 1900,
        "plot_size_cents": 8.0,
        "bedrooms": 3,
        "bathrooms": 3,
        "floors": 2,
        "parking_spaces": 1,
        "balconies": 2,
        "kitchen_type": "Modular",
        "quality": "Standard",
        "roof_type": "RCC",
        "flooring": "Vitrified Tile",
        "price": 6400000.0
    }
]
